# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x17\n\x07request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x65mpty2-\n\x04test\x12%\n\x05hello\x12\r.test.request\x1a\x0b.test.empty\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_EMPTY = DESCRIPTOR.message_types_by_name['empty']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.request)
  })
_sym_db.RegisterMessage(request)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.empty)
  })
_sym_db.RegisterMessage(empty)

_TEST = DESCRIPTOR.services_by_name['test']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=43
  _EMPTY._serialized_start=45
  _EMPTY._serialized_end=52
  _TEST._serialized_start=54
  _TEST._serialized_end=99
# @@protoc_insertion_point(module_scope)
